"""Generate human-readable API documentation from normalized endpoint data."""

import json
from pathlib import Path
from urllib.parse import urlparse


CATEGORY_ORDER = [
    "Search",
    "Stocks - Real-time Quotes",
    "Stocks - Price History",
    "ETFs - Real-time Quotes",
    "ETFs - Price History",
    "Markets - Mini Charts",
    "Screener - Stocks",
    "Screener - ETFs",
    "Other",
]

CATEGORY_DESCRIPTIONS = {
    "Search": "Global search across stocks, ETFs, and international symbols. Returns ranked results by relevance.",
    "Stocks - Real-time Quotes": "Real-time stock price and trading data. Polled periodically by the frontend to update price widgets.",
    "Stocks - Price History": "Historical OHLCV data for stocks. Used to render price history charts and financial tables.",
    "ETFs - Real-time Quotes": "Real-time ETF price and volume data.",
    "ETFs - Price History": "Historical price data for ETFs.",
    "Markets - Mini Charts": "Mini sparkline chart data for the market status widget (pre-market, regular hours, after-hours).",
    "Screener - Stocks": "Stock screener API. Accepts filter, sort, and pagination parameters.",
    "Screener - ETFs": "ETF screener API.",
    "Other": "Miscellaneous internal endpoints.",
}


def format_response_preview(preview) -> str:
    if preview is None:
        return "_No JSON response captured_"
    try:
        text = json.dumps(preview, indent=2, default=str)
        if len(text) > 1200:
            text = text[:1200] + "\n  ... (truncated)"
        return f"```json\n{text}\n```"
    except Exception:
        return f"```\n{str(preview)[:600]}\n```"


def format_query_params(query_params: dict) -> str:
    if not query_params:
        return "_none_"
    parts = []
    for key in sorted(query_params.keys()):
        value = query_params[key]
        if value:
            parts.append(f"`{key}` (example: `{value}`)")
        else:
            parts.append(f"`{key}`")
    return ", ".join(parts)


def generate_docs(normalized_path: str = "output/normalized.json",
                  output_path: str = "output/api_docs.md") -> str:
    with open(normalized_path) as f:
        endpoints = json.load(f)

    # Group by category
    by_category: dict[str, list] = {}
    for ep in endpoints:
        cat = ep.get("category", "Other")
        by_category.setdefault(cat, []).append(ep)

    lines = [
        "# stockanalysis.com Internal API Documentation",
        "",
        "> Auto-generated by crawling stockanalysis.com with an authenticated Playwright session.",
        "> Base URL: `https://stockanalysis.com`",
        "> All endpoints use `{ticker}` as a placeholder for a stock or ETF symbol (lowercase).",
        "> Stock endpoints use prefix `/s/`, ETF endpoints use `/e/`.",
        "",
        "## Table of Contents",
        "",
    ]

    for cat in CATEGORY_ORDER:
        if cat in by_category:
            count = len(by_category[cat])
            anchor = cat.lower().replace(" ", "-").replace("/", "").replace("--", "-")
            lines.append(f"- [{cat}](#{anchor}) ({count} endpoint{'s' if count != 1 else ''})")

    total = len(endpoints)
    lines += [
        "",
        "---",
        "",
        f"**Total unique API endpoints:** {total}",
        "",
        "---",
        "",
    ]

    for cat in CATEGORY_ORDER:
        if cat not in by_category:
            continue

        cat_endpoints = by_category[cat]
        anchor = cat.lower().replace(" ", "-").replace("/", "").replace("--", "-")

        lines.append(f"## {cat}")
        lines.append("")
        if cat in CATEGORY_DESCRIPTIONS:
            lines.append(CATEGORY_DESCRIPTIONS[cat])
            lines.append("")

        for ep in cat_endpoints:
            method = ep.get("method", "GET")
            norm_url = ep.get("normalized_url", "")
            example_url = ep.get("example_url", "")
            query_params = ep.get("query_params", {})
            status = ep.get("status", "?")
            occurrences = ep.get("occurrences", 1)
            post_data = ep.get("post_data")
            preview = ep.get("response_preview")

            parsed = urlparse(norm_url)
            path_display = parsed.path
            if parsed.query:
                path_display += "?" + parsed.query

            lines.append(f"### `{method}` {path_display}")
            lines.append("")
            lines.append(f"- **Example URL:** `{example_url}`")
            lines.append(f"- **Status:** `{status}`")
            lines.append(f"- **Query params:** {format_query_params(query_params)}")
            lines.append(f"- **Observed:** {occurrences} time(s)")

            if post_data:
                lines.append("- **Request body:**")
                lines.append("  ```")
                lines.append(f"  {str(post_data)[:400]}")
                lines.append("  ```")

            lines.append("")
            lines.append("**Response preview:**")
            lines.append("")
            lines.append(format_response_preview(preview))
            lines.append("")
            lines.append("---")
            lines.append("")

    doc = "\n".join(lines)
    Path(output_path).parent.mkdir(exist_ok=True)
    with open(output_path, "w") as f:
        f.write(doc)

    print(f"Documentation written to {output_path} ({total} endpoints, {len(by_category)} categories)")
    return doc


if __name__ == "__main__":
    generate_docs()
